;;; apparmor-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from apparmor-mode.el

(autoload 'apparmor-mode "apparmor-mode" "\
apparmor-mode is a major mode for editing AppArmor profiles.

(fn)" t)
(autoload 'apparmor-mode-setup-flymake-backend "apparmor-mode" "\
Setup the `flymake' backend for `apparmor-mode'.")
(add-hook 'apparmor-mode-hook 'apparmor-mode-setup-flymake-backend)
(add-to-list 'auto-mode-alist '("\\`/etc/apparmor\\.d/" . apparmor-mode))
(add-to-list 'auto-mode-alist '("\\`/var/lib/snapd/apparmor/profiles/" . apparmor-mode))
(register-definition-prefixes "apparmor-mode" '("apparmor-mode-"))

;;; End of scraped data

(provide 'apparmor-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; apparmor-mode-autoloads.el ends here
